% EREBOS
% This script adds the supplementary trials to complete the matrix Hyperion
% generated by Ouranos. It also adds two columns, runs and post-pause
% trials. 
% Receiving a 977*7 matrix, it builds a 1011*9 matrix.

subject = subj;
inilen=975;  % initial length
finlen=1011; % final length
runlen=[180 159 159 159 159 159]; % run lengths
pplen=[6 9 6 9 6]; % post-pause length

sumrunlen=[];
for i=1:6
    sumrunlen=[sumrunlen sum(runlen(1:i))];
end
sumpplen=[];
for i=1:5
    sumpplen=[sumpplen sum(pplen(1:i))];
end

FullDesignMatrix=zeros(inilen,9);

% A: 1st and last value of initial blocks
% B: 1st and last value of final blocks
% C: 1st and last value of post-pause trials

A=[1,sumrunlen(1);
    sumrunlen(1)+1,sumrunlen(2);
    sumrunlen(2)+1,sumrunlen(3);
    sumrunlen(3)+1,sumrunlen(4);
    sumrunlen(4)+1,sumrunlen(5);
    sumrunlen(5)+1,sumrunlen(6)];

B=[1,sumrunlen(1);
    sumrunlen(1)+sumpplen(1)+1,sumrunlen(2)+sumpplen(1);
    sumrunlen(2)+sumpplen(2)+1,sumrunlen(3)+sumpplen(2);
    sumrunlen(3)+sumpplen(3)+1,sumrunlen(4)+sumpplen(3);
    sumrunlen(4)+sumpplen(4)+1,sumrunlen(5)+sumpplen(4);
    sumrunlen(5)+sumpplen(5)+1,sumrunlen(6)+sumpplen(5)];

C=[sumrunlen(1)+1,sumrunlen(1)+sumpplen(1);
    sumrunlen(2)+sumpplen(1)+1,sumrunlen(2)+sumpplen(2);
    sumrunlen(3)+sumpplen(2)+1,sumrunlen(3)+sumpplen(3);
    sumrunlen(4)+sumpplen(3)+1,sumrunlen(4)+sumpplen(4);
    sumrunlen(5)+sumpplen(4)+1,sumrunlen(5)+sumpplen(5)];

% Takes the values
for i=1:6
    FullDesignMatrix(B(i,1):B(i,2),1:7)=DesignMatrix(A(i,1):A(i,2),:);
end

%% Column 1: episodes
FullDesignMatrix(C(1,1):C(1,2),1)=4;
FullDesignMatrix(C(2,1):C(2,2),1)=8;
FullDesignMatrix(C(3,1):C(3,2),1)=12;
FullDesignMatrix(C(4,1):C(4,2),1)=16;
FullDesignMatrix(C(5,1):C(5,2),1)=20;

%% Column 2: task-sets
if session==1
    
    FullDesignMatrix(C(1,1):C(1,2),2)=3;
    FullDesignMatrix(C(2,1):C(2,2),2)=2;
    FullDesignMatrix(C(3,1):C(3,2),2)=3;
    FullDesignMatrix(C(4,1):C(4,2),2)=2;
    FullDesignMatrix(C(5,1):C(5,2),2)=2;
    
elseif session==2
    
    FullDesignMatrix(C(1,1):C(1,2),2)=4;
    FullDesignMatrix(C(2,1):C(2,2),2)=8;
    FullDesignMatrix(C(3,1):C(3,2),2)=12;
    FullDesignMatrix(C(4,1):C(4,2),2)=16;
    FullDesignMatrix(C(5,1):C(5,2),2)=20;
    
end

%% Column 3: stimuli
a=Shuffle([repmat(1,1,2),repmat(2,1,2),repmat(3,1,2)]);
b=Shuffle([repmat(1,1,3),repmat(2,1,3),repmat(3,1,3)]);
c=Shuffle([repmat(1,1,2),repmat(2,1,2),repmat(3,1,2)]);
d=Shuffle([repmat(1,1,3),repmat(2,1,3),repmat(3,1,3)]);
e=Shuffle([repmat(1,1,2),repmat(2,1,2),repmat(3,1,2)]);

FullDesignMatrix(C(1,1):C(1,2),3)=a;
FullDesignMatrix(C(2,1):C(2,2),3)=b;
FullDesignMatrix(C(3,1):C(3,2),3)=c;
FullDesignMatrix(C(4,1):C(4,2),3)=d;
FullDesignMatrix(C(5,1):C(5,2),3)=e;

%% Column 4: expected response
if session==1
    load S_Metis
    ts1=z(3*(subject-1)+1,1:4);
    ts2=z(3*(subject-1)+2,1:4);
    ts3=z(3*(subject-1)+3,1:4);
    for i=1:6
        FullDesignMatrix(C(1,1)+(i-1),4)=find(ts3==FullDesignMatrix(C(1,1)+(i-1),3));
    end
    for i=1:9
        FullDesignMatrix(C(2,1)+(i-1),4)=find(ts2==FullDesignMatrix(C(2,1)+(i-1),3));
    end
    for i=1:6
        FullDesignMatrix(C(3,1)+(i-1),4)=find(ts3==FullDesignMatrix(C(3,1)+(i-1),3));
    end
    for i=1:9
        FullDesignMatrix(C(4,1)+(i-1),4)=find(ts2==FullDesignMatrix(C(4,1)+(i-1),3));
    end
    for i=1:6
        FullDesignMatrix(C(5,1)+(i-1),4)=find(ts2==FullDesignMatrix(C(5,1)+(i-1),3));
    end   
    
elseif session==2
    load C_Metis
    ts4=z(24*(subject-1)+4,1:4);
    ts8=z(24*(subject-1)+8,1:4);
    ts12=z(24*(subject-1)+12,1:4);
    ts16=z(24*(subject-1)+16,1:4);
    ts20=z(24*(subject-1)+20,1:4);
    for i=1:6
        FullDesignMatrix(C(1,1)+(i-1),4)=find(ts4==FullDesignMatrix(C(1,1)+(i-1),3));
    end
    for i=1:9
        FullDesignMatrix(C(2,1)+(i-1),4)=find(ts8==FullDesignMatrix(C(2,1)+(i-1),3));
    end
    for i=1:6
        FullDesignMatrix(C(3,1)+(i-1),4)=find(ts12==FullDesignMatrix(C(3,1)+(i-1),3));
    end
    for i=1:9
        FullDesignMatrix(C(4,1)+(i-1),4)=find(ts16==FullDesignMatrix(C(4,1)+(i-1),3));
    end
    for i=1:6
        FullDesignMatrix(C(5,1)+(i-1),4)=find(ts20==FullDesignMatrix(C(5,1)+(i-1),3));
    end   
    
end

%% Column 5: true and trap trials
d=Shuffle([zeros(5,1);1]);
e=Shuffle([zeros(8,1);1]);
f=Shuffle([zeros(5,1);1]);
g=Shuffle([zeros(8,1);1]);
h=Shuffle([zeros(5,1);1]);

FullDesignMatrix(C(1,1):C(1,2),5)=d;
FullDesignMatrix(C(2,1):C(2,2),5)=e;
FullDesignMatrix(C(3,1):C(3,2),5)=f;
FullDesignMatrix(C(4,1):C(4,2),5)=g;
FullDesignMatrix(C(5,1):C(5,2),5)=h;

%% Column 6 and 7: jitters
% jitval=[0.4, 0.1; 0.4, 1.85;0.4, 3.6;...
%     2.15, 0.1;2.15, 1.85;2.15, 3.6;...
%     3.9, 0.1;3.9, 1.85;3.9, 3.6];
% 
% g=[Shuffle(jitval(:,1)) Shuffle(jitval(:,1)) Shuffle(jitval(:,1)) Shuffle(jitval(:,1))];
% h=[Shuffle(jitval(:,2)) Shuffle(jitval(:,2)) Shuffle(jitval(:,2)) Shuffle(jitval(:,2))];

FullDesignMatrix(C(1,1):C(1,2),6)= jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(6,1);
FullDesignMatrix(C(2,1):C(2,2),6)= jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(9,1);
FullDesignMatrix(C(3,1):C(3,2),6)= jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(6,1);
FullDesignMatrix(C(4,1):C(4,2),6)= jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(9,1);
FullDesignMatrix(C(5,1):C(5,2),6)= jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(6,1);

FullDesignMatrix(C(1,1):C(1,2),7)= jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(6,1);
FullDesignMatrix(C(2,1):C(2,2),7)= jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(9,1);
FullDesignMatrix(C(3,1):C(3,2),7)= jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(6,1);
FullDesignMatrix(C(4,1):C(4,2),7)= jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(9,1);
FullDesignMatrix(C(5,1):C(5,2),7)= jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(6,1);

FullDesignMatrix(inilen:finlen,6) = jittervalues(1,1) + (jittervalues(1,2)-jittervalues(1,1)).*rand(size(inilen:finlen, 2),1);
FullDesignMatrix(inilen:finlen,7) = jittervalues(2,1) + (jittervalues(2,2)-jittervalues(2,1)).*rand(size(inilen:finlen, 2),1);




%% Column 8: runs
r=[ones(runlen(1),1);2*ones(runlen(2)+pplen(1),1);3*ones(runlen(3)+pplen(2),1);...
    4*ones(runlen(4)+pplen(3),1);5*ones(runlen(5)+pplen(4),1);6*ones(runlen(6)+pplen(5),1)];
FullDesignMatrix(:,8)=r;

%% Column 9: post-pause trials
pp=zeros(finlen,1);

pp(C(1,1):C(1,2))=1;
pp(C(2,1):C(2,2))=1;
pp(C(3,1):C(3,2))=1;
pp(C(4,1):C(4,2))=1;
pp(C(5,1):C(5,2))=1;

FullDesignMatrix(:,9)=pp;

clear a b c d e f g1 g2 h1 h2 i1 i2 r pp jitval

